version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11  # Replace with your desired Python version
    resource_class: small
    steps:
      - checkout
      - run:
          name: Set Up Python Environment
          command: |
            python -m venv venv
            . venv/bin/activate
      - run:
          name: Install Dependencies (if any)
          command: |
            if [ -f requirements.txt ]; then
                pip install -r requirements.txt
            fi
            pip install pytest
      - run:
          name: Run Tests and Generate JUnit Report
          command: |
            mkdir test-results
            TEST_FILES=$(circleci tests glob "**/test_*.py")
            echo "$TEST_FILES" | circleci tests run --command="xargs pytest -o junit_family=legacy --junitxml=test-results/junit.xml" --verbose
workflows:
  build_and_test_workflow:
    jobs:
      - build-and-test
